travis:
  secure:
    BINSTAR_TOKEN: i20pRO+Oz7RgCIHASBqszu64NtT3VFOpcjqs2ThJ1Fxd7GI7zrK6eRywWREsxiVwcL+kFIOdzhTRVpzfsnCRvgvDYJGpLfR+XOHh+sFS8oYPUV51CYsZlTEFqBPw3bYqbe0AaMLo3kLfv3m1U85wcDLPTOR4bomAnxwLgFB4IeV96gfMEgJcYc722brwtAhRFamjjEo5CkzK2+6bulx4o68mwX94XOxAzujnyaeuvdcvIp47bi0yCrxeTsqqfCM+MhjlLWwDc4T3EzkbzqmPghHL0VVxAfaXNhxT8h6ZcXNQjFk7G1HcfGbrbc8ZqeIjQpQZHyK4d91JvmnEX/A+S4TxIPLV2TObvLTtUCCSzxR8Mp6LC6pC3nvBvJtvXT6W+U6eAGZG7froP6oqsFTBtLDMaYFjH3uh+V6gqiCkKhdXwQKNBy5atk80nfA+ayi+U4IaiH8BfvixjygJiWS3yvdJVTTmF2GiuQLGHZ6ItkHUzdib3zXL+sVwlvnYWJduewK6/X9M1V+bztM9dQS1DR20kj2trUNtsHlvKZVh7rGL0vVzv5SpCRYc8e27lUxluuVrae6kcBh6bv/CNndClQFmKUcdG7iBkzCliME7tWpvIFBTcmdefHExR27V32qWIh99yPc1EKsBuvUt9fnbxLimJFGlfD8BFaJiJY5r7VM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
